chotot: https://xe.chotot.com
regions_v2_url: "https://gateway.chotot.com/v1/public/web-proxy-api/loadRegionsV2"
ad_listing_video_url: "https://gateway.chotot.com/v1/public/ad-listing-video"
cg_car: 2010

